[package]
name = "basisu-sys"
version = "0.1.0"
edition = "2024"

[target.'cfg(target_arch = "wasm32")'.dependencies]
basisu-bindgen = { path = "../basisu-bindgen" }
wasm-bindgen = "0.2.106"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
basisu-vendor = { path = "../basisu-vendor" }
