[package]
name = "test_scene"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
name = "test_scene_lib"
crate-type = ["lib", "cdylib"]

[dependencies]
bevy = { version = "0.17" }
bevy_basisu_loader = { path = "../.." }
